### ISSUE TITLE
How can I detect and skip silent parts when streaming?

### ISSUE THREAD

**Issue by cerupcat** [StevenKuo/AudioUnitSample#2]
I'd like to be able to skip any silent parts in the audio. Do you know how I coudl do this?

For example, on a podcast, if someone stops speaking for 2 seconds, I'd like to shorten this so there isn't a big pause.

**Comment by StevenKuo** [comment]
Is your podcast live ? If not, I think you have to filter the audio data that is no human voice before storing to buffer.
I don't know how to do it, but I think It related about pitch detection. You can do some searching for that.
